### ISSUE TITLE
Request to order GeneralCategory enum by order in Unicode spec

### ISSUE THREAD

**Issue by csmclaren** [yeslogic/unicode-general-category#8]
Hello,

In lib.rs, the definition of enum GeneralCategory alphabetically orders its variants. This request is to reorder those variants to match their order in https://unicode.org/reports/tr44/#General_Category_Values, 5.7.1, Table 12. and derive PartialOrd on the enum.

The purpose of this request is to allow clients to use one or two comparators to determine if a character is within a certain range. For example < OtherLetter would mean *any* letter, as the Unicode spec groups categories such that the first five categories are all letters. With your library, a client current requires more comparisons for common groups.

**Comment by wezm** [comment]
Hmm the enum is generated by https://github.com/yeslogic/ucd-generate in <https://github.com/yeslogic/ucd-generate/blob/master/src/general_category.rs>.

A `BTreeMap` is involved, which is where the ordering comes from. The [Unicode Character Database](https://www.unicode.org/Public/15.0.0/ucd/) (UCD) is the source of the data but I'm not sure if the ordering you're after is published in the UCD (happy to be wrong here).

**Comment by csmclaren** [comment]
Hi! Thanks for your quick response! I agree that the ordering is not published in the UCD itself. It is in the annex mentioned above, which I believe is normative. That said, there is no specific mention in the annex that the ordering in the table is fixed.

In light of the fact it's autogenerated, and my particular use-case is admittedly not strong (it's essentially a micro-optimization), I'm happy to close. Thanks again for the consideration!

Side-note: As I was thinking about this more, I realized that there are only 30 categories (and this has been stable for many years), each of which could be represented by a single bit in a 32-bit word. I can easily calculate the bit representation for each category by taking 1 and shifting it left by the variant's discriminant (1 << 0, 1 << 1, etc.). I can then use these values to build bit masks for things like 'any of the letter categories', etc. This, in my opinion, is a better solution than checking ranges of values as per my original request anyway.
